### ISSUE TITLE
i have a complied problem

### ISSUE THREAD

**Issue by natthanank** [usnistgov/trec_eval#15]
cygwin show this error when i compile 
how can i fix this?

`m_ndcg.c:13:8: error: expected ‘)’ before ‘/’ token        
 double log2(double x);
        ^
In file included from sysfunc.h:21:0,
                 from m_ndcg_cut.c:8:
m_ndcg_cut.c:12:8: error: expected ‘)’ before ‘/’ token
 double log2(double x);
        ^
In file included from sysfunc.h:21:0,
                 from m_Rndcg.c:9:
m_Rndcg.c:13:8: error: expected ‘)’ before ‘/’ token
 double log2(double x);
        ^
In file included from sysfunc.h:21:0,
                 from m_ndcg_rel.c:9:
m_ndcg_rel.c:13:8: error: expected ‘)’ before ‘/’ token
 double log2(double x);
        ^
In file included from sysfunc.h:21:0,
                 from m_binG.c:9:
m_binG.c:13:8: error: expected ‘)’ before ‘/’ token
 double log2(double x);
        ^
In file included from sysfunc.h:21:0,
                 from m_G.c:9:
m_G.c:13:8: error: expected ‘)’ before ‘/’ token
 double log2(double x);
        ^
make: *** [Makefile:54: trec_eval] Error 1
`

**Comment by bobTabor25** [comment]
Do you still have the problem ?

**Comment by bobTabor25** [comment]
check this link : https://github.com/bobTabor25/trec_eval.exe
