### ISSUE TITLE
can we permit comments in results and qrel files?

### ISSUE THREAD

**Issue by cmacdonald** [usnistgov/trec_eval#20]
please.

**Comment by isoboroff** [comment]
Yes.  Line-oriented comments marked with a # at the start of the line to EOL is easy to implement, and while qrels files wouldn't be backwards compatible they can be made so with grep -v.

**Comment by cmacdonald** [comment]
for qrels, do you have qids starting with #?

**Comment by isoboroff** [comment]
Not in TREC.  trec_eval didn't even support non-numeric qids before v8.

**Comment by isoboroff** [comment]
Maybe we should head comments with something really old and obscure like DNL, as a salute to our auguft heritage.

**Comment by cmacdonald** [comment]
why qrels files wouldn't be backwards compatible if we allowed # comments?

**Comment by isoboroff** [comment]
Craig, I included test cases but please let me know if you see any anomalies.

**Comment by isoboroff** [comment]
Missing documentation.  Comments are lines starting with # and ending with a newline.

**Comment by cmacdonald** [comment]
The malformed line numbers are useful. Can I check they aren't upset when we skip comment lines?

**Comment by isoboroff** [comment]
Don't quite understand... test case?  The code skips comment lines both when allocating and reading, so not sure which line numbers you mean.

**Comment by isoboroff** [comment]
Added documentation string in commit ce3a5df5002df4c5ef6092b8ced56c06942dac2a

**Comment by cmacdonald** [comment]
Thanks Ian. Documentation looks suffice.

Re line numbers. Consider this example malformed qrels file:
```
1 0 1
```

If I use that, I get the following error:
```
$ trec_eval9 badqrel oneres.res 
trec_eval.get_qrels: Malformed line 1
```

My question was, with your patch, are the malformed line numbers after comments still correct?
i.e. the malformed line number for a qrel file below would still be line number 2?
```
#this is a comment
1 0 1
```

[This line of the patch](https://github.com/usnistgov/trec_eval/pull/23/files#diff-254d45e07d78ea331c5672e1b52aabbeR117) makes me think not, but the code below looks OK.
