### ISSUE TITLE
Licensing information

### ISSUE THREAD

**Issue by zeuner** [usnistgov/trec_eval#42]
The repository doesn't contain any licensing information. Adding it might ease the integration in software packaging systems.

**Comment by isoboroff** [comment]
There is a license in 10.0-rc2, you can see it at f222e22fb8c50c81b106e5d143d80a381ff7028e.  This is the standard license for NIST software, which is MIT-ish, and includes a bit extra to cover things that are copyrighted (which were pre-NIST) and which are not.
