### ISSUE TITLE
Installation On Windows

### ISSUE THREAD

**Issue by saeid-p** [usnistgov/trec_eval#6]
The installation process on Windows is not clear. What are the requirements and what script to run to compile and use trec_eval? I understand that it is a C program, but how to compile it on my machine? IS there any compiled version somewhere that I can use on e.g. Windows 7?

**Comment by isoboroff** [comment]
I just merged a pull request onto to 10-dev branch that should allow compilation under Cygwin.  I've asked that author if they can get me some documentation on how to compile under Windows... we're a Unix shop here.
